name: Test that hercules successfully builds

on:
  pull_request:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
        - macos-10.15
        - macos-11
        - ubuntu-18.04
        - ubuntu-20.04
        compiler:
        - gcc
        - clang
        exclude:
        - os: ubuntu-20.04
          compiler: clang
        include:
        - os: windows-latest
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: Install Ubuntu dependencies
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt-get install -y regina-rexx libregina3-dev
        sudo apt-get install -y binutils binutils-dev
    - name: Install macOS dependencies
      if: ${{ runner.os == 'macOS' }}
      run: |
        brew install gawk gsed automake regina-rexx
    - name: Build
      if: ${{ runner.os != 'Windows' }}
      run: |
        if [ "${{ matrix.compiler }}" = "gcc" ]; then
          export CC="gcc"
          export CXX=g++
        else
          export CC="clang"
          export CXX="clang++"
        fi
        if [ "${{ runner.os }}" = "macOS" ]; then
          export CC="$(xcrun --find $CC) -arch x86_64"
          export CXX="$(xcrun --find $CXX) -arch x86_64"
          export SDKROOT="$(xcrun --show-sdk-path)"
          export CFLAGS="-I/usr/local/include"
          export CXXFLAGS="-I/usr/local/include"
        fi
        util/bldlvlck
        ./autogen.sh
        ./configure --enable-regina-rexx --enable-setuid-hercifc
        ./config.status --config
        NUM_JOBS=1
        if command -v nproc >/dev/null; then
          NUM_JOBS=$(nproc)
        elif [ "${{ runner.os }}" = "macOS" ]; then
          NUM_JOBS=$(sysctl -n hw.physicalcpu)
        fi
        make -j$NUM_JOBS
        make check
    - name: Build
      if: ${{ runner.os == 'Windows' }}
      run: ./makefile.bat DEBUG-X64 makefile.msvc 8
